### ISSUE TITLE
Does this work

### ISSUE THREAD

**Issue by GhostingGodzilla** [Classes123/SB-Synchronization#1]

**Comment by GhostingGodzilla** [comment]
I install everything and I don't see any permission
not sure if I put everything in the right place we're supposed to be

**Comment by GhostingGodzilla** [comment]
#0 src/XF/Admin/Controller/AddOn.php(841): XF\AddOn\AddOn->checkRequirements(Array, Array)
#1 src/XF/Admin/Controller/AddOn.php(357): XF\Admin\Controller\AddOn->getAddOnWarningsAndErrors(Object(XF\AddOn\AddOn))
#2 src/XF/Mvc/Dispatcher.php(352): XF\Admin\Controller\AddOn->actionRebuild(Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Dispatcher.php(258): XF\Mvc\Dispatcher->dispatchClass('XF:AddOn', 'Rebuild', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn), NULL)
#4 src/XF/Mvc/Dispatcher.php(115): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn), NULL)
#5 src/XF/Mvc/Dispatcher.php(57): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(2483): XF\Mvc\Dispatcher->run()
#7 src/XF.php(524): XF\App->run()
#8 admin.php(13): XF::runApp('XF\\Admin\\App')
#9 {main}

**Comment by GhostingGodzilla** [comment]
Error: Class "\dev\Setup" not found src/XF/AddOn/AddOn.php:455

**Comment by Classes123** [comment]
> #0 src/XF/Admin/Controller/AddOn.php(841): XF\AddOn\AddOn->checkRequirements(Array, Array) #1 src/XF/Admin/Controller/AddOn.php(357): XF\Admin\Controller\AddOn->getAddOnWarningsAndErrors(Object(XF\AddOn\AddOn)) #2 src/XF/Mvc/Dispatcher.php(352): XF\Admin\Controller\AddOn->actionRebuild(Object(XF\Mvc\ParameterBag)) #3 src/XF/Mvc/Dispatcher.php(258): XF\Mvc\Dispatcher->dispatchClass('XF:AddOn', 'Rebuild', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn), NULL) #4 src/XF/Mvc/Dispatcher.php(115): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn), NULL) #5 src/XF/Mvc/Dispatcher.php(57): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch)) #6 src/XF/App.php(2483): XF\Mvc\Dispatcher->run() #7 src/XF.php(524): XF\App->run() #8 admin.php(13): XF::runApp('XF\Admin\App') #9 {main}

xenforo version?

**Comment by GhostingGodzilla** [comment]
v2.2.12

**Comment by GhostingGodzilla** [comment]
Any news

**Comment by Classes123** [comment]
> Any news

I'm sorry, I have serious health problems, as soon as I check, I'll let you know

**Comment by Classes123** [comment]
So, I'm not dead. Please describe how to reproduce this issue. Also check that you have installed the version from the [releases](https://github.com/Classes123/SB-Synchronization/releases), not the dev version.
